### ISSUE TITLE
OS X App?

### ISSUE THREAD

**Issue by moon47usaco** [victorchee/JavaScriptCoreDemo#1]
How to do the same in OS X Application?

Thank you.

**Comment by victorchee** [comment]
JavaScriptCore framework support from macOS 10.5.

**Comment by moon47usaco** [comment]
JavaScriptCore framework has support but not the same.

This code does not work on OS X please see my attempt to use this in OS X project.

https://github.com/moon47usaco/JSCore-Test-03

Thank you. =]

**Comment by victorchee** [comment]
In macOS, you can get JSContext like this:
func webView(_ sender: WebView!, didFinishLoadFor frame: WebFrame!)
    {
        let jsContext = frame.javaScriptContext // or like this: JSContext(jsGlobalContextRef: frame.globalContext)
}

**Comment by moon47usaco** [comment]
Thank you so much... =]

For some reason the alert button does not work but it is unimportant to me.
I only need the native.functionInSwift and that works now with your suggestion.
